// Liste complète des pays du monde avec codes ISO2
export const COUNTRIES = [
  { code: 'AD', name: 'Andorre', flag: '🇦🇩', dialCode: '+376' },
  { code: 'AE', name: 'Émirats arabes unis', flag: '🇦🇪', dialCode: '+971' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93' },
  { code: 'AG', name: 'Antigua-et-Barbuda', flag: '🇦🇬', dialCode: '+1268' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮', dialCode: '+1264' },
  { code: 'AL', name: 'Albanie', flag: '🇦🇱', dialCode: '+355' },
  { code: 'AM', name: 'Arménie', flag: '🇦🇲', dialCode: '+374' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', dialCode: '+244' },
  { code: 'AQ', name: 'Antarctique', flag: '🇦🇶', dialCode: '+672' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷', dialCode: '+54' },
  { code: 'AS', name: 'Samoa américaines', flag: '🇦🇸', dialCode: '+1684' },
  { code: 'AT', name: 'Autriche', flag: '🇦🇹', dialCode: '+43' },
  { code: 'AU', name: 'Australie', flag: '🇦🇺', dialCode: '+61' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼', dialCode: '+297' },
  { code: 'AX', name: 'Îles Åland', flag: '🇦🇽', dialCode: '+358' },
  { code: 'AZ', name: 'Azerbaïdjan', flag: '🇦🇿', dialCode: '+994' },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦', dialCode: '+387' },
  { code: 'BB', name: 'Barbade', flag: '🇧🇧', dialCode: '+1246' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪', dialCode: '+32' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226' },
  { code: 'BG', name: 'Bulgarie', flag: '🇧🇬', dialCode: '+359' },
  { code: 'BH', name: 'Bahreïn', flag: '🇧🇭', dialCode: '+973' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', dialCode: '+257' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯', dialCode: '+229' },
  { code: 'BL', name: 'Saint-Barthélemy', flag: '🇧🇱', dialCode: '+590' },
  { code: 'BM', name: 'Bermudes', flag: '🇧🇲', dialCode: '+1441' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', dialCode: '+673' },
  { code: 'BO', name: 'Bolivie', flag: '🇧🇴', dialCode: '+591' },
  { code: 'BQ', name: 'Bonaire, Saint-Eustache et Saba', flag: '🇧🇶', dialCode: '+599' },
  { code: 'BR', name: 'Brésil', flag: '🇧🇷', dialCode: '+55' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', dialCode: '+1242' },
  { code: 'BT', name: 'Bhoutan', flag: '🇧🇹', dialCode: '+975' },
  { code: 'BV', name: 'Île Bouvet', flag: '🇧🇻', dialCode: '+47' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', dialCode: '+267' },
  { code: 'BY', name: 'Biélorussie', flag: '🇧🇾', dialCode: '+375' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', dialCode: '+501' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', dialCode: '+1' },
  { code: 'CC', name: 'Îles Cocos', flag: '🇨🇨', dialCode: '+61' },
  { code: 'CD', name: 'République démocratique du Congo', flag: '🇨🇩', dialCode: '+243' },
  { code: 'CF', name: 'République centrafricaine', flag: '🇨🇫', dialCode: '+236' },
  { code: 'CG', name: 'République du Congo', flag: '🇨🇬', dialCode: '+242' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭', dialCode: '+41' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', dialCode: '+225' },
  { code: 'CK', name: 'Îles Cook', flag: '🇨🇰', dialCode: '+682' },
  { code: 'CL', name: 'Chili', flag: '🇨🇱', dialCode: '+56' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲', dialCode: '+237' },
  { code: 'CN', name: 'Chine', flag: '🇨🇳', dialCode: '+86' },
  { code: 'CO', name: 'Colombie', flag: '🇨🇴', dialCode: '+57' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', dialCode: '+53' },
  { code: 'CV', name: 'Cap-Vert', flag: '🇨🇻', dialCode: '+238' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼', dialCode: '+599' },
  { code: 'CX', name: 'Île Christmas', flag: '🇨🇽', dialCode: '+61' },
  { code: 'CY', name: 'Chypre', flag: '🇨🇾', dialCode: '+357' },
  { code: 'CZ', name: 'République tchèque', flag: '🇨🇿', dialCode: '+420' },
  { code: 'DE', name: 'Allemagne', flag: '🇩🇪', dialCode: '+49' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', dialCode: '+253' },
  { code: 'DK', name: 'Danemark', flag: '🇩🇰', dialCode: '+45' },
  { code: 'DM', name: 'Dominique', flag: '🇩🇲', dialCode: '+1767' },
  { code: 'DO', name: 'République dominicaine', flag: '🇩🇴', dialCode: '+1809' },
  { code: 'DZ', name: 'Algérie', flag: '🇩🇿', dialCode: '+213' },
  { code: 'EC', name: 'Équateur', flag: '🇪🇨', dialCode: '+593' },
  { code: 'EE', name: 'Estonie', flag: '🇪🇪', dialCode: '+372' },
  { code: 'EG', name: 'Égypte', flag: '🇪🇬', dialCode: '+20' },
  { code: 'EH', name: 'Sahara occidental', flag: '🇪🇭', dialCode: '+212' },
  { code: 'ER', name: 'Érythrée', flag: '🇪🇷', dialCode: '+291' },
  { code: 'ES', name: 'Espagne', flag: '🇪🇸', dialCode: '+34' },
  { code: 'ET', name: 'Éthiopie', flag: '🇪🇹', dialCode: '+251' },
  { code: 'FI', name: 'Finlande', flag: '🇫🇮', dialCode: '+358' },
  { code: 'FJ', name: 'Fidji', flag: '🇫🇯', dialCode: '+679' },
  { code: 'FK', name: 'Îles Malouines', flag: '🇫🇰', dialCode: '+500' },
  { code: 'FM', name: 'Micronésie', flag: '🇫🇲', dialCode: '+691' },
  { code: 'FO', name: 'Îles Féroé', flag: '🇫🇴', dialCode: '+298' },
  { code: 'FR', name: 'France', flag: '🇫🇷', dialCode: '+33' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', dialCode: '+241' },
  { code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧', dialCode: '+44' },
  { code: 'GD', name: 'Grenade', flag: '🇬🇩', dialCode: '+1473' },
  { code: 'GE', name: 'Géorgie', flag: '🇬🇪', dialCode: '+995' },
  { code: 'GF', name: 'Guyane française', flag: '🇬🇫', dialCode: '+594' },
  { code: 'GG', name: 'Guernesey', flag: '🇬🇬', dialCode: '+44' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', dialCode: '+233' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮', dialCode: '+350' },
  { code: 'GL', name: 'Groenland', flag: '🇬🇱', dialCode: '+299' },
  { code: 'GM', name: 'Gambie', flag: '🇬🇲', dialCode: '+220' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳', dialCode: '+224' },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', dialCode: '+590' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶', dialCode: '+240' },
  { code: 'GR', name: 'Grèce', flag: '🇬🇷', dialCode: '+30' },
  { code: 'GS', name: 'Géorgie du Sud-et-les Îles Sandwich du Sud', flag: '🇬🇸', dialCode: '+500' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', dialCode: '+502' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺', dialCode: '+1671' },
  { code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼', dialCode: '+245' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', dialCode: '+592' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', dialCode: '+852' },
  { code: 'HM', name: 'Îles Heard-et-MacDonald', flag: '🇭🇲', dialCode: '+672' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', dialCode: '+504' },
  { code: 'HR', name: 'Croatie', flag: '🇭🇷', dialCode: '+385' },
  { code: 'HT', name: 'Haïti', flag: '🇭🇹', dialCode: '+509' },
  { code: 'HU', name: 'Hongrie', flag: '🇭🇺', dialCode: '+36' },
  { code: 'ID', name: 'Indonésie', flag: '🇮🇩', dialCode: '+62' },
  { code: 'IE', name: 'Irlande', flag: '🇮🇪', dialCode: '+353' },
  { code: 'IL', name: 'Israël', flag: '🇮🇱', dialCode: '+972' },
  { code: 'IM', name: 'Île de Man', flag: '🇮🇲', dialCode: '+44' },
  { code: 'IN', name: 'Inde', flag: '🇮🇳', dialCode: '+91' },
  { code: 'IO', name: 'Territoire britannique de l\'océan Indien', flag: '🇮🇴', dialCode: '+246' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶', dialCode: '+964' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', dialCode: '+98' },
  { code: 'IS', name: 'Islande', flag: '🇮🇸', dialCode: '+354' },
  { code: 'IT', name: 'Italie', flag: '🇮🇹', dialCode: '+39' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪', dialCode: '+44' },
  { code: 'JM', name: 'Jamaïque', flag: '🇯🇲', dialCode: '+1876' },
  { code: 'JO', name: 'Jordanie', flag: '🇯🇴', dialCode: '+962' },
  { code: 'JP', name: 'Japon', flag: '🇯🇵', dialCode: '+81' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', dialCode: '+254' },
  { code: 'KG', name: 'Kirghizistan', flag: '🇰🇬', dialCode: '+996' },
  { code: 'KH', name: 'Cambodge', flag: '🇰🇭', dialCode: '+855' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', dialCode: '+686' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲', dialCode: '+269' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', flag: '🇰🇳', dialCode: '+1869' },
  { code: 'KP', name: 'Corée du Nord', flag: '🇰🇵', dialCode: '+850' },
  { code: 'KR', name: 'Corée du Sud', flag: '🇰🇷', dialCode: '+82' },
  { code: 'KW', name: 'Koweït', flag: '🇰🇼', dialCode: '+965' },
  { code: 'KY', name: 'Îles Caïmans', flag: '🇰🇾', dialCode: '+1345' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', dialCode: '+856' },
  { code: 'LB', name: 'Liban', flag: '🇱🇧', dialCode: '+961' },
  { code: 'LC', name: 'Sainte-Lucie', flag: '🇱🇨', dialCode: '+1758' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', dialCode: '+231' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', dialCode: '+266' },
  { code: 'LT', name: 'Lituanie', flag: '🇱🇹', dialCode: '+370' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352' },
  { code: 'LV', name: 'Lettonie', flag: '🇱🇻', dialCode: '+371' },
  { code: 'LY', name: 'Libye', flag: '🇱🇾', dialCode: '+218' },
  { code: 'MA', name: 'Maroc', flag: '🇲🇦', dialCode: '+212' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', dialCode: '+377' },
  { code: 'MD', name: 'Moldavie', flag: '🇲🇩', dialCode: '+373' },
  { code: 'ME', name: 'Monténégro', flag: '🇲🇪', dialCode: '+382' },
  { code: 'MF', name: 'Saint-Martin', flag: '🇲🇫', dialCode: '+590' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', dialCode: '+261' },
  { code: 'MH', name: 'Îles Marshall', flag: '🇲🇭', dialCode: '+692' },
  { code: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰', dialCode: '+389' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', dialCode: '+223' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', dialCode: '+95' },
  { code: 'MN', name: 'Mongolie', flag: '🇲🇳', dialCode: '+976' },
  { code: 'MO', name: 'Macao', flag: '🇲🇴', dialCode: '+853' },
  { code: 'MP', name: 'Îles Mariannes du Nord', flag: '🇲🇵', dialCode: '+1670' },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶', dialCode: '+596' },
  { code: 'MR', name: 'Mauritanie', flag: '🇲🇷', dialCode: '+222' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸', dialCode: '+1664' },
  { code: 'MT', name: 'Malte', flag: '🇲🇹', dialCode: '+356' },
  { code: 'MU', name: 'Maurice', flag: '🇲🇺', dialCode: '+230' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', dialCode: '+960' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', dialCode: '+265' },
  { code: 'MX', name: 'Mexique', flag: '🇲🇽', dialCode: '+52' },
  { code: 'MY', name: 'Malaisie', flag: '🇲🇾', dialCode: '+60' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', dialCode: '+258' },
  { code: 'NA', name: 'Namibie', flag: '🇳🇦', dialCode: '+264' },
  { code: 'NC', name: 'Nouvelle-Calédonie', flag: '🇳🇨', dialCode: '+687' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', dialCode: '+227' },
  { code: 'NF', name: 'Île Norfolk', flag: '🇳🇫', dialCode: '+672' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', dialCode: '+234' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', dialCode: '+505' },
  { code: 'NL', name: 'Pays-Bas', flag: '🇳🇱', dialCode: '+31' },
  { code: 'NO', name: 'Norvège', flag: '🇳🇴', dialCode: '+47' },
  { code: 'NP', name: 'Népal', flag: '🇳🇵', dialCode: '+977' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', dialCode: '+674' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺', dialCode: '+683' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿', dialCode: '+64' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', dialCode: '+968' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', dialCode: '+507' },
  { code: 'PE', name: 'Pérou', flag: '🇵🇪', dialCode: '+51' },
  { code: 'PF', name: 'Polynésie française', flag: '🇵🇫', dialCode: '+689' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬', dialCode: '+675' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', dialCode: '+63' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', dialCode: '+92' },
  { code: 'PL', name: 'Pologne', flag: '🇵🇱', dialCode: '+48' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', flag: '🇵🇲', dialCode: '+508' },
  { code: 'PN', name: 'Îles Pitcairn', flag: '🇵🇳', dialCode: '+870' },
  { code: 'PR', name: 'Porto Rico', flag: '🇵🇷', dialCode: '+1787' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', dialCode: '+970' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', dialCode: '+351' },
  { code: 'PW', name: 'Palaos', flag: '🇵🇼', dialCode: '+680' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', dialCode: '+595' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', dialCode: '+974' },
  { code: 'RE', name: 'La Réunion', flag: '🇷🇪', dialCode: '+262' },
  { code: 'RO', name: 'Roumanie', flag: '🇷🇴', dialCode: '+40' },
  { code: 'RS', name: 'Serbie', flag: '🇷🇸', dialCode: '+381' },
  { code: 'RU', name: 'Russie', flag: '🇷🇺', dialCode: '+7' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', dialCode: '+250' },
  { code: 'SA', name: 'Arabie saoudite', flag: '🇸🇦', dialCode: '+966' },
  { code: 'SB', name: 'Îles Salomon', flag: '🇸🇧', dialCode: '+677' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', dialCode: '+248' },
  { code: 'SD', name: 'Soudan', flag: '🇸🇩', dialCode: '+249' },
  { code: 'SE', name: 'Suède', flag: '🇸🇪', dialCode: '+46' },
  { code: 'SG', name: 'Singapour', flag: '🇸🇬', dialCode: '+65' },
  { code: 'SH', name: 'Sainte-Hélène', flag: '🇸🇭', dialCode: '+290' },
  { code: 'SI', name: 'Slovénie', flag: '🇸🇮', dialCode: '+386' },
  { code: 'SJ', name: 'Svalbard et Jan Mayen', flag: '🇸🇯', dialCode: '+47' },
  { code: 'SK', name: 'Slovaquie', flag: '🇸🇰', dialCode: '+421' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232' },
  { code: 'SM', name: 'Saint-Marin', flag: '🇸🇲', dialCode: '+378' },
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳', dialCode: '+221' },
  { code: 'SO', name: 'Somalie', flag: '🇸🇴', dialCode: '+252' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', dialCode: '+597' },
  { code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸', dialCode: '+211' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', flag: '🇸🇹', dialCode: '+239' },
  { code: 'SV', name: 'Salvador', flag: '🇸🇻', dialCode: '+503' },
  { code: 'SX', name: 'Saint-Martin', flag: '🇸🇽', dialCode: '+1721' },
  { code: 'SY', name: 'Syrie', flag: '🇸🇾', dialCode: '+963' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', dialCode: '+268' },
  { code: 'TC', name: 'Îles Turques-et-Caïques', flag: '🇹🇨', dialCode: '+1649' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩', dialCode: '+235' },
  { code: 'TF', name: 'Terres australes françaises', flag: '🇹🇫', dialCode: '+262' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', dialCode: '+228' },
  { code: 'TH', name: 'Thaïlande', flag: '🇹🇭', dialCode: '+66' },
  { code: 'TJ', name: 'Tadjikistan', flag: '🇹🇯', dialCode: '+992' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰', dialCode: '+690' },
  { code: 'TL', name: 'Timor oriental', flag: '🇹🇱', dialCode: '+670' },
  { code: 'TM', name: 'Turkménistan', flag: '🇹🇲', dialCode: '+993' },
  { code: 'TN', name: 'Tunisie', flag: '🇹🇳', dialCode: '+216' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', dialCode: '+676' },
  { code: 'TR', name: 'Turquie', flag: '🇹🇷', dialCode: '+90' },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹', dialCode: '+1868' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', dialCode: '+688' },
  { code: 'TW', name: 'Taïwan', flag: '🇹🇼', dialCode: '+886' },
  { code: 'TZ', name: 'Tanzanie', flag: '🇹🇿', dialCode: '+255' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', dialCode: '+380' },
  { code: 'UG', name: 'Ouganda', flag: '🇺🇬', dialCode: '+256' },
  { code: 'UM', name: 'Îles mineures éloignées des États-Unis', flag: '🇺🇲', dialCode: '+1' },
  { code: 'US', name: 'États-Unis', flag: '🇺🇸', dialCode: '+1' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', dialCode: '+598' },
  { code: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿', dialCode: '+998' },
  { code: 'VA', name: 'Vatican', flag: '🇻🇦', dialCode: '+39' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨', dialCode: '+1784' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', dialCode: '+58' },
  { code: 'VG', name: 'Îles Vierges britanniques', flag: '🇻🇬', dialCode: '+1284' },
  { code: 'VI', name: 'Îles Vierges des États-Unis', flag: '🇻🇮', dialCode: '+1340' },
  { code: 'VN', name: 'Viêt Nam', flag: '🇻🇳', dialCode: '+84' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', dialCode: '+678' },
  { code: 'WF', name: 'Wallis-et-Futuna', flag: '🇼🇫', dialCode: '+681' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', dialCode: '+685' },
  { code: 'YE', name: 'Yémen', flag: '🇾🇪', dialCode: '+967' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹', dialCode: '+262' },
  { code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', dialCode: '+27' },
  { code: 'ZM', name: 'Zambie', flag: '🇿🇲', dialCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263' }
];

// Pays populaires pour un affichage prioritaire
export const POPULAR_COUNTRIES = [
  'GN', 'FR', 'US', 'GB', 'DE', 'ES', 'IT', 'CN', 'JP', 'CA',
  'SN', 'ML', 'CI', 'BF', 'NG', 'GH', 'BR', 'MX', 'IN', 'AU'
];

export const getCountryByCode = (code: string) => {
  return COUNTRIES.find(country => country.code === code);
};

export const searchCountries = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return COUNTRIES.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.code.toLowerCase().includes(lowerQuery)
  );
};